<template>
  <!-- Off-screen print layout captured by exportReport(). Fixed 794px width
       (A4 at 96dpi) so PDF and PNG look the same whatever the viewport is.
       Content mirrors the Result page / History record detail: status,
       three metrics, recommendations. -->
  <div class="export-root" aria-hidden="true">
    <section v-for="(rec, i) in records" :key="i" class="report-page" data-report-page>
      <header class="rp-header">
        <div>
          <p class="rp-brand">VocaSense</p>
          <h1 class="rp-title">Voice Analysis Report</h1>
        </div>
        <p class="rp-date">{{ rec.dateLabel }}<br />{{ rec.time }}</p>
      </header>

      <div class="rp-disclaimer">
        <strong>Medical Disclaimer:</strong> This platform provides preliminary voice health insights and does not replace professional medical diagnosis. Please consult a healthcare professional for medical concerns.
      </div>

      <div class="rp-status">
        <span class="rp-badge" :class="'risk-bg-' + rec.risk">{{ rec.resultLabel }}</span>
        <h2 class="rp-status-title">Your Voice Health Status</h2>
        <p v-if="rec.subtitle" class="rp-status-sub">{{ rec.subtitle }}</p>
      </div>

      <div class="rp-metrics">
        <div v-for="m in rec.metrics" :key="m.kind" class="rp-metric" :class="'metric-bg-' + m.level">
          <span class="rp-metric-name">{{ m.label }}</span>
          <strong class="rp-metric-value" :class="'risk-text-' + m.level">{{ m.value }}</strong>
        </div>
      </div>

      <h3 class="rp-section">Personalized Recommendations</h3>
      <div class="rp-recs">
        <div v-for="r in rec.recommendations" :key="r.text" class="rp-rec" :class="'priority-bg-' + r.priority">
          <span class="rp-rec-dot" :class="'priority-dot-' + r.priority"></span>
          <span class="rp-rec-text">{{ r.text }}</span>
          <span class="rp-rec-prio" :class="'priority-text-' + r.priority">{{ r.priority === 'high' ? 'High' : 'Moderate' }} Priority</span>
        </div>
      </div>

      <footer class="rp-footer">
        <span>Generated by VocaSense</span>
        <span v-if="records.length > 1">{{ i + 1 }} / {{ records.length }}</span>
      </footer>
    </section>
  </div>
</template>

<script setup>
defineProps({
  // [{ dateLabel, time, risk, resultLabel, subtitle?, metrics, recommendations }]
  records: { type: Array, required: true }
})
</script>

<style scoped>
.export-root {
  position: fixed;
  left: -10000px;
  top: 0;
  pointer-events: none;
  font-family: 'Poppins', sans-serif;
}

.report-page {
  box-sizing: border-box;
  width: 794px;
  min-height: 1123px;
  padding: 48px 52px 36px;
  background: #fff;
  display: flex;
  flex-direction: column;
  gap: 20px;
  color: #1a1a2e;
}

.rp-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  padding-bottom: 16px;
  border-bottom: 2px solid #6594e4;
}
.rp-brand { margin: 0; font-size: 13px; font-weight: 700; color: #6594e4; letter-spacing: 1px; }
.rp-title { margin: 2px 0 0; font-size: 26px; font-weight: 700; }
.rp-date { margin: 0; font-size: 12.5px; font-weight: 500; color: #6b7690; text-align: right; line-height: 1.6; }

.rp-disclaimer {
  background: #d9e6fc;
  border: 1px solid rgba(101, 148, 228, 0.3);
  border-radius: 12px;
  padding: 12px 16px;
  font-size: 12px;
  line-height: 1.6;
  color: #3d5a99;
}

.rp-status { text-align: center; display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 12px 0 4px; }
.rp-badge { padding: 6px 18px; border-radius: 20px; font-size: 13px; font-weight: 600; }
.rp-status-title { margin: 4px 0 0; font-size: 22px; font-weight: 700; }
.rp-status-sub { margin: 0; font-size: 13px; font-weight: 600; color: #6b7590; }

.rp-metrics { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; }
.rp-metric {
  border-radius: 16px;
  border: 1px solid rgba(0, 0, 0, 0.06);
  padding: 18px 16px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.rp-metric-name { font-size: 12.5px; font-weight: 500; color: #5b6680; }
.rp-metric-value { font-size: 18px; font-weight: 700; }

.rp-section { margin: 8px 0 0; font-size: 16px; font-weight: 700; }
.rp-recs { display: flex; flex-direction: column; gap: 8px; }
.rp-rec { display: flex; align-items: center; gap: 12px; border-radius: 12px; padding: 12px 14px; }
.rp-rec-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
.rp-rec-text { flex: 1; font-size: 13px; font-weight: 600; line-height: 1.5; }
.rp-rec-prio { font-size: 11px; font-weight: 600; white-space: nowrap; }

.rp-footer {
  margin-top: auto;
  display: flex;
  justify-content: space-between;
  padding-top: 12px;
  border-top: 1px solid #eef1f8;
  font-size: 10.5px;
  font-weight: 500;
  color: #8b96ad;
}

.risk-bg-low { background: #e3f7ec; color: #1f9d5b; }
.risk-bg-moderate { background: #fff3dc; color: #b7791f; }
.risk-bg-high { background: #fdeaea; color: #c83d3d; }
.risk-text-low { color: #1f9d5b; }
.risk-text-moderate { color: #b7791f; }
.risk-text-high { color: #c83d3d; }
.metric-bg-low { background: linear-gradient(135deg, #ffffff 3%, #f1ffee 66%, #e0ffe0 100%); }
.metric-bg-moderate { background: linear-gradient(135deg, #ffffff 3%, #fffdf4 66%, #fff5e0 100%); }
.metric-bg-high { background: linear-gradient(135deg, #ffffff 3%, #fff4f4 66%, #ffe0e0 100%); }
.priority-bg-high { background: #ffe5e0; }
.priority-bg-moderate { background: #fff5e0; }
.priority-dot-high { background: linear-gradient(135deg, #ff8686, #f43333); }
.priority-dot-moderate { background: linear-gradient(135deg, #ffb886, #f47033); }
.priority-text-high { color: #c83d3d; }
.priority-text-moderate { color: #c68e3f; }
</style>
